name: Deploy Cormparse Frontend
run-name: cormparse frontend service ci-cd workflow
on:
  push:
    branches:
      - "master"
jobs:
  build_publish_docker_image:
    name: Test, Build And Publish cormparse frontend service docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.1.0
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config: pageLoadTimeout=100000,baseUrl=http://localhost:3000
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
          command: npm run test:run
      # compile next production build
      - name: Compile next production build
        run: npm run build
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            masterpiecekodz/cormparse_frontend
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=v1.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: false
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "masterpiecekodz/cormparse_frontend:latest"
          format: "table"
          exit-code: "1"
          vuln-type: "os,library"
          severity: "CRITICAL"
          ignore-unfixed: true
      # I am pushhing manually bcos I want to be sure there is no vulnerability before pushing image.
      - run: docker push masterpiecekodz/cormparse_frontend:1.0.0
      - run: docker push masterpiecekodz/cormparse_frontend:latest
